// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: server/center.proto

package xsf_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中心服相关协议定义
// center connector --> center 握手
type Cc_C_Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ports    []uint32 `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *Cc_C_Handshake) Reset() {
	*x = Cc_C_Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_Handshake) ProtoMessage() {}

func (x *Cc_C_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_Handshake.ProtoReflect.Descriptor instead.
func (*Cc_C_Handshake) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{0}
}

func (x *Cc_C_Handshake) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Cc_C_Handshake) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

// center  --> center connector 握手反馈
type C_Cc_Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NewId    uint32   `protobuf:"varint,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	Ports    []uint32 `protobuf:"varint,3,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *C_Cc_Handshake) Reset() {
	*x = C_Cc_Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_Handshake) ProtoMessage() {}

func (x *C_Cc_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_Handshake.ProtoReflect.Descriptor instead.
func (*C_Cc_Handshake) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{1}
}

func (x *C_Cc_Handshake) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *C_Cc_Handshake) GetNewId() uint32 {
	if x != nil {
		return x.NewId
	}
	return 0
}

func (x *C_Cc_Handshake) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

// center connector --> center 心跳
type Cc_C_Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Cc_C_Heartbeat) Reset() {
	*x = Cc_C_Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_Heartbeat) ProtoMessage() {}

func (x *Cc_C_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_Heartbeat.ProtoReflect.Descriptor instead.
func (*Cc_C_Heartbeat) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{2}
}

// 服务器信息
type MSG_ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器ID
	Ip       string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                              // 服务器内部IP
	Ports    []uint32 `protobuf:"varint,3,rep,packed,name=ports,proto3" json:"ports,omitempty"`                // 端口信息
	Status   uint32   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *MSG_ServerInfo) Reset() {
	*x = MSG_ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_ServerInfo) ProtoMessage() {}

func (x *MSG_ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_ServerInfo.ProtoReflect.Descriptor instead.
func (*MSG_ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{3}
}

func (x *MSG_ServerInfo) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *MSG_ServerInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MSG_ServerInfo) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *MSG_ServerInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// connector --> center 上行服务器信息数据
type Cc_C_ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*MSG_ServerInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"` // 所有信息
}

func (x *Cc_C_ServerInfo) Reset() {
	*x = Cc_C_ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_ServerInfo) ProtoMessage() {}

func (x *Cc_C_ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_ServerInfo.ProtoReflect.Descriptor instead.
func (*Cc_C_ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{4}
}

func (x *Cc_C_ServerInfo) GetInfos() []*MSG_ServerInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// center --> connector 下行服务器信息数据
type C_Cc_ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*MSG_ServerInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"` // 所有信息
}

func (x *C_Cc_ServerInfo) Reset() {
	*x = C_Cc_ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_ServerInfo) ProtoMessage() {}

func (x *C_Cc_ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_ServerInfo.ProtoReflect.Descriptor instead.
func (*C_Cc_ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{5}
}

func (x *C_Cc_ServerInfo) GetInfos() []*MSG_ServerInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// connector --> center 服务器离线
type Cc_C_ServerLost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *Cc_C_ServerLost) Reset() {
	*x = Cc_C_ServerLost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_ServerLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_ServerLost) ProtoMessage() {}

func (x *Cc_C_ServerLost) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_ServerLost.ProtoReflect.Descriptor instead.
func (*Cc_C_ServerLost) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{6}
}

func (x *Cc_C_ServerLost) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// center --> connector 服务器离线
type C_Cc_ServerLost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *C_Cc_ServerLost) Reset() {
	*x = C_Cc_ServerLost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_ServerLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_ServerLost) ProtoMessage() {}

func (x *C_Cc_ServerLost) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_ServerLost.ProtoReflect.Descriptor instead.
func (*C_Cc_ServerLost) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{7}
}

func (x *C_Cc_ServerLost) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// connector --> center 服务器已准备好
type Cc_C_ServerOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *Cc_C_ServerOk) Reset() {
	*x = Cc_C_ServerOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_ServerOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_ServerOk) ProtoMessage() {}

func (x *Cc_C_ServerOk) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_ServerOk.ProtoReflect.Descriptor instead.
func (*Cc_C_ServerOk) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{8}
}

func (x *Cc_C_ServerOk) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// center --> connector 服务器已准备好
type C_Cc_ServerOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *C_Cc_ServerOk) Reset() {
	*x = C_Cc_ServerOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_ServerOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_ServerOk) ProtoMessage() {}

func (x *C_Cc_ServerOk) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_ServerOk.ProtoReflect.Descriptor instead.
func (*C_Cc_ServerOk) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{9}
}

func (x *C_Cc_ServerOk) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// center --> connector 关服
type C_Cc_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C_Cc_Stop) Reset() {
	*x = C_Cc_Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_Stop) ProtoMessage() {}

func (x *C_Cc_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_Stop.ProtoReflect.Descriptor instead.
func (*C_Cc_Stop) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{10}
}

// connector --> center 设置时间穿越
type Cc_C_TimePass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimePass uint32 `protobuf:"varint,1,opt,name=time_pass,json=timePass,proto3" json:"time_pass,omitempty"`
}

func (x *Cc_C_TimePass) Reset() {
	*x = Cc_C_TimePass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cc_C_TimePass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cc_C_TimePass) ProtoMessage() {}

func (x *Cc_C_TimePass) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cc_C_TimePass.ProtoReflect.Descriptor instead.
func (*Cc_C_TimePass) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{11}
}

func (x *Cc_C_TimePass) GetTimePass() uint32 {
	if x != nil {
		return x.TimePass
	}
	return 0
}

// center --> connector 设置时间穿越
type C_Cc_TimePass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimePass uint32 `protobuf:"varint,1,opt,name=time_pass,json=timePass,proto3" json:"time_pass,omitempty"`
}

func (x *C_Cc_TimePass) Reset() {
	*x = C_Cc_TimePass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_center_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Cc_TimePass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Cc_TimePass) ProtoMessage() {}

func (x *C_Cc_TimePass) ProtoReflect() protoreflect.Message {
	mi := &file_server_center_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Cc_TimePass.ProtoReflect.Descriptor instead.
func (*C_Cc_TimePass) Descriptor() ([]byte, []int) {
	return file_server_center_proto_rawDescGZIP(), []int{12}
}

func (x *C_Cc_TimePass) GetTimePass() uint32 {
	if x != nil {
		return x.TimePass
	}
	return 0
}

var File_server_center_proto protoreflect.FileDescriptor

var file_server_center_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x22, 0x43, 0x0a,
	0x0e, 0x43, 0x63, 0x5f, 0x43, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x22, 0x5a, 0x0a, 0x0e, 0x43, 0x5f, 0x43, 0x63, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6e, 0x65, 0x77, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x10,
	0x0a, 0x0e, 0x43, 0x63, 0x5f, 0x43, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x22, 0x6b, 0x0a, 0x0e, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a,
	0x0f, 0x43, 0x63, 0x5f, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x3f,
	0x0a, 0x0f, 0x43, 0x5f, 0x43, 0x63, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22,
	0x2e, 0x0a, 0x0f, 0x43, 0x63, 0x5f, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x2e, 0x0a, 0x0f, 0x43, 0x5f, 0x43, 0x63, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x2c, 0x0a, 0x0d, 0x43, 0x63, 0x5f, 0x43, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6b,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a,
	0x0d, 0x43, 0x5f, 0x43, 0x63, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x6b, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x43,
	0x5f, 0x43, 0x63, 0x5f, 0x53, 0x74, 0x6f, 0x70, 0x22, 0x2c, 0x0a, 0x0d, 0x43, 0x63, 0x5f, 0x43,
	0x5f, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x22, 0x2c, 0x0a, 0x0d, 0x43, 0x5f, 0x43, 0x63, 0x5f, 0x54,
	0x69, 0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x50, 0x61, 0x73, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x62, 0x2f, 0x78, 0x73, 0x66, 0x5f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_center_proto_rawDescOnce sync.Once
	file_server_center_proto_rawDescData = file_server_center_proto_rawDesc
)

func file_server_center_proto_rawDescGZIP() []byte {
	file_server_center_proto_rawDescOnce.Do(func() {
		file_server_center_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_center_proto_rawDescData)
	})
	return file_server_center_proto_rawDescData
}

var file_server_center_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_center_proto_goTypes = []interface{}{
	(*Cc_C_Handshake)(nil),  // 0: NLD_PB.Cc_C_Handshake
	(*C_Cc_Handshake)(nil),  // 1: NLD_PB.C_Cc_Handshake
	(*Cc_C_Heartbeat)(nil),  // 2: NLD_PB.Cc_C_Heartbeat
	(*MSG_ServerInfo)(nil),  // 3: NLD_PB.MSG_ServerInfo
	(*Cc_C_ServerInfo)(nil), // 4: NLD_PB.Cc_C_ServerInfo
	(*C_Cc_ServerInfo)(nil), // 5: NLD_PB.C_Cc_ServerInfo
	(*Cc_C_ServerLost)(nil), // 6: NLD_PB.Cc_C_ServerLost
	(*C_Cc_ServerLost)(nil), // 7: NLD_PB.C_Cc_ServerLost
	(*Cc_C_ServerOk)(nil),   // 8: NLD_PB.Cc_C_ServerOk
	(*C_Cc_ServerOk)(nil),   // 9: NLD_PB.C_Cc_ServerOk
	(*C_Cc_Stop)(nil),       // 10: NLD_PB.C_Cc_Stop
	(*Cc_C_TimePass)(nil),   // 11: NLD_PB.Cc_C_TimePass
	(*C_Cc_TimePass)(nil),   // 12: NLD_PB.C_Cc_TimePass
}
var file_server_center_proto_depIdxs = []int32{
	3, // 0: NLD_PB.Cc_C_ServerInfo.infos:type_name -> NLD_PB.MSG_ServerInfo
	3, // 1: NLD_PB.C_Cc_ServerInfo.infos:type_name -> NLD_PB.MSG_ServerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_center_proto_init() }
func file_server_center_proto_init() {
	if File_server_center_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_center_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_ServerLost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_ServerLost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_ServerOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_ServerOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cc_C_TimePass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_center_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Cc_TimePass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_center_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_center_proto_goTypes,
		DependencyIndexes: file_server_center_proto_depIdxs,
		MessageInfos:      file_server_center_proto_msgTypes,
	}.Build()
	File_server_center_proto = out.File
	file_server_center_proto_rawDesc = nil
	file_server_center_proto_goTypes = nil
	file_server_center_proto_depIdxs = nil
}
