// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: server/gate.proto

package xsf_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gate --> gate acceptor 握手
type Gt_GtA_Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器id
}

func (x *Gt_GtA_Handshake) Reset() {
	*x = Gt_GtA_Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gt_GtA_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gt_GtA_Handshake) ProtoMessage() {}

func (x *Gt_GtA_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gt_GtA_Handshake.ProtoReflect.Descriptor instead.
func (*Gt_GtA_Handshake) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{0}
}

func (x *Gt_GtA_Handshake) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// gate acceptor --> gate  握手反馈
type GtA_Gt_Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器id
}

func (x *GtA_Gt_Handshake) Reset() {
	*x = GtA_Gt_Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtA_Gt_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtA_Gt_Handshake) ProtoMessage() {}

func (x *GtA_Gt_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtA_Gt_Handshake.ProtoReflect.Descriptor instead.
func (*GtA_Gt_Handshake) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{1}
}

func (x *GtA_Gt_Handshake) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// gate --> gate acceptor 心跳
type Gt_GtA_Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gt_GtA_Heartbeat) Reset() {
	*x = Gt_GtA_Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gt_GtA_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gt_GtA_Heartbeat) ProtoMessage() {}

func (x *Gt_GtA_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gt_GtA_Heartbeat.ProtoReflect.Descriptor instead.
func (*Gt_GtA_Heartbeat) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{2}
}

// gate --> gate acceptor 客户端连接关闭
type Gt_GtA_ClientClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId uint32 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *Gt_GtA_ClientClose) Reset() {
	*x = Gt_GtA_ClientClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gt_GtA_ClientClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gt_GtA_ClientClose) ProtoMessage() {}

func (x *Gt_GtA_ClientClose) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gt_GtA_ClientClose.ProtoReflect.Descriptor instead.
func (*Gt_GtA_ClientClose) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{3}
}

func (x *Gt_GtA_ClientClose) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// gate acceptor --> gate 主动关闭客户端连接
type GtA_Gt_ClientDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId uint32 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Reason   uint32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GtA_Gt_ClientDisconnect) Reset() {
	*x = GtA_Gt_ClientDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtA_Gt_ClientDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtA_Gt_ClientDisconnect) ProtoMessage() {}

func (x *GtA_Gt_ClientDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtA_Gt_ClientDisconnect.ProtoReflect.Descriptor instead.
func (*GtA_Gt_ClientDisconnect) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{4}
}

func (x *GtA_Gt_ClientDisconnect) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GtA_Gt_ClientDisconnect) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// gate acceptor --> gate 发往客户端消息
type GtA_Gt_ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId      []uint32 `protobuf:"varint,1,rep,packed,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientMessage []byte   `protobuf:"bytes,2,opt,name=client_message,json=clientMessage,proto3" json:"client_message,omitempty"`
}

func (x *GtA_Gt_ClientMessage) Reset() {
	*x = GtA_Gt_ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtA_Gt_ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtA_Gt_ClientMessage) ProtoMessage() {}

func (x *GtA_Gt_ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtA_Gt_ClientMessage.ProtoReflect.Descriptor instead.
func (*GtA_Gt_ClientMessage) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{5}
}

func (x *GtA_Gt_ClientMessage) GetClientId() []uint32 {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *GtA_Gt_ClientMessage) GetClientMessage() []byte {
	if x != nil {
		return x.ClientMessage
	}
	return nil
}

// gate acceptor --> gate 消息广播
type GtA_Gt_Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientMessage []byte `protobuf:"bytes,1,opt,name=client_message,json=clientMessage,proto3" json:"client_message,omitempty"`
}

func (x *GtA_Gt_Broadcast) Reset() {
	*x = GtA_Gt_Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtA_Gt_Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtA_Gt_Broadcast) ProtoMessage() {}

func (x *GtA_Gt_Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtA_Gt_Broadcast.ProtoReflect.Descriptor instead.
func (*GtA_Gt_Broadcast) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{6}
}

func (x *GtA_Gt_Broadcast) GetClientMessage() []byte {
	if x != nil {
		return x.ClientMessage
	}
	return nil
}

// gate acceptor --> gate 设置服务器id
type GtA_Gt_SetServerID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId uint32 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Ep       uint32 `protobuf:"varint,2,opt,name=ep,proto3" json:"ep,omitempty"`
	ServerId uint32 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *GtA_Gt_SetServerID) Reset() {
	*x = GtA_Gt_SetServerID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_gate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtA_Gt_SetServerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtA_Gt_SetServerID) ProtoMessage() {}

func (x *GtA_Gt_SetServerID) ProtoReflect() protoreflect.Message {
	mi := &file_server_gate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtA_Gt_SetServerID.ProtoReflect.Descriptor instead.
func (*GtA_Gt_SetServerID) Descriptor() ([]byte, []int) {
	return file_server_gate_proto_rawDescGZIP(), []int{7}
}

func (x *GtA_Gt_SetServerID) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GtA_Gt_SetServerID) GetEp() uint32 {
	if x != nil {
		return x.Ep
	}
	return 0
}

func (x *GtA_Gt_SetServerID) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

var File_server_gate_proto protoreflect.FileDescriptor

var file_server_gate_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x22, 0x2f, 0x0a, 0x10, 0x47,
	0x74, 0x5f, 0x47, 0x74, 0x41, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x10,
	0x47, 0x74, 0x41, 0x5f, 0x47, 0x74, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x74, 0x5f, 0x47, 0x74, 0x41, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x74, 0x5f, 0x47, 0x74, 0x41, 0x5f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x17, 0x47, 0x74, 0x41, 0x5f, 0x47, 0x74, 0x5f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x14, 0x47, 0x74, 0x41, 0x5f, 0x47, 0x74, 0x5f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x39, 0x0a, 0x10, 0x47, 0x74, 0x41, 0x5f, 0x47, 0x74, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5e, 0x0a, 0x12, 0x47,
	0x74, 0x41, 0x5f, 0x47, 0x74, 0x5f, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x65, 0x70, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x70,
	0x62, 0x2f, 0x78, 0x73, 0x66, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_gate_proto_rawDescOnce sync.Once
	file_server_gate_proto_rawDescData = file_server_gate_proto_rawDesc
)

func file_server_gate_proto_rawDescGZIP() []byte {
	file_server_gate_proto_rawDescOnce.Do(func() {
		file_server_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_gate_proto_rawDescData)
	})
	return file_server_gate_proto_rawDescData
}

var file_server_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_server_gate_proto_goTypes = []interface{}{
	(*Gt_GtA_Handshake)(nil),        // 0: NLD_PB.Gt_GtA_Handshake
	(*GtA_Gt_Handshake)(nil),        // 1: NLD_PB.GtA_Gt_Handshake
	(*Gt_GtA_Heartbeat)(nil),        // 2: NLD_PB.Gt_GtA_Heartbeat
	(*Gt_GtA_ClientClose)(nil),      // 3: NLD_PB.Gt_GtA_ClientClose
	(*GtA_Gt_ClientDisconnect)(nil), // 4: NLD_PB.GtA_Gt_ClientDisconnect
	(*GtA_Gt_ClientMessage)(nil),    // 5: NLD_PB.GtA_Gt_ClientMessage
	(*GtA_Gt_Broadcast)(nil),        // 6: NLD_PB.GtA_Gt_Broadcast
	(*GtA_Gt_SetServerID)(nil),      // 7: NLD_PB.GtA_Gt_SetServerID
}
var file_server_gate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_gate_proto_init() }
func file_server_gate_proto_init() {
	if File_server_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gt_GtA_Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtA_Gt_Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gt_GtA_Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gt_GtA_ClientClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtA_Gt_ClientDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtA_Gt_ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtA_Gt_Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_gate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtA_Gt_SetServerID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_gate_proto_goTypes,
		DependencyIndexes: file_server_gate_proto_depIdxs,
		MessageInfos:      file_server_gate_proto_msgTypes,
	}.Build()
	File_server_gate_proto = out.File
	file_server_gate_proto_rawDesc = nil
	file_server_gate_proto_goTypes = nil
	file_server_gate_proto_depIdxs = nil
}
