// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: server/mail.proto

package xsf_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送邮件物品
type MSG_SendMailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 物品ID
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *MSG_SendMailItem) Reset() {
	*x = MSG_SendMailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_SendMailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_SendMailItem) ProtoMessage() {}

func (x *MSG_SendMailItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_SendMailItem.ProtoReflect.Descriptor instead.
func (*MSG_SendMailItem) Descriptor() ([]byte, []int) {
	return file_server_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_SendMailItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MSG_SendMailItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// server --> mail 发送邮件
type S_Ml_SendMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorId uint32              `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	MailId  uint32              `protobuf:"varint,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Title   string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body    string              `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Items   []*MSG_SendMailItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	MailMsg []string            `protobuf:"bytes,6,rep,name=mail_msg,json=mailMsg,proto3" json:"mail_msg,omitempty"`
	ReqId   uint64              `protobuf:"varint,7,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
}

func (x *S_Ml_SendMail) Reset() {
	*x = S_Ml_SendMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_Ml_SendMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_Ml_SendMail) ProtoMessage() {}

func (x *S_Ml_SendMail) ProtoReflect() protoreflect.Message {
	mi := &file_server_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_Ml_SendMail.ProtoReflect.Descriptor instead.
func (*S_Ml_SendMail) Descriptor() ([]byte, []int) {
	return file_server_mail_proto_rawDescGZIP(), []int{1}
}

func (x *S_Ml_SendMail) GetActorId() uint32 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *S_Ml_SendMail) GetMailId() uint32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *S_Ml_SendMail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *S_Ml_SendMail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *S_Ml_SendMail) GetItems() []*MSG_SendMailItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *S_Ml_SendMail) GetMailMsg() []string {
	if x != nil {
		return x.MailMsg
	}
	return nil
}

func (x *S_Ml_SendMail) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

var File_server_mail_proto protoreflect.FileDescriptor

var file_server_mail_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x22, 0x38, 0x0a, 0x10, 0x4d,
	0x53, 0x47, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x53, 0x5f, 0x4d, 0x6c, 0x5f, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4e, 0x4c, 0x44, 0x5f, 0x50, 0x42, 0x2e, 0x4d, 0x53,
	0x47, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x73, 0x67,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x62, 0x2f, 0x78, 0x73,
	0x66, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_mail_proto_rawDescOnce sync.Once
	file_server_mail_proto_rawDescData = file_server_mail_proto_rawDesc
)

func file_server_mail_proto_rawDescGZIP() []byte {
	file_server_mail_proto_rawDescOnce.Do(func() {
		file_server_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_mail_proto_rawDescData)
	})
	return file_server_mail_proto_rawDescData
}

var file_server_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_mail_proto_goTypes = []interface{}{
	(*MSG_SendMailItem)(nil), // 0: NLD_PB.MSG_SendMailItem
	(*S_Ml_SendMail)(nil),    // 1: NLD_PB.S_Ml_SendMail
}
var file_server_mail_proto_depIdxs = []int32{
	0, // 0: NLD_PB.S_Ml_SendMail.items:type_name -> NLD_PB.MSG_SendMailItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_mail_proto_init() }
func file_server_mail_proto_init() {
	if File_server_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_SendMailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_Ml_SendMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_mail_proto_goTypes,
		DependencyIndexes: file_server_mail_proto_depIdxs,
		MessageInfos:      file_server_mail_proto_msgTypes,
	}.Build()
	File_server_mail_proto = out.File
	file_server_mail_proto_rawDesc = nil
	file_server_mail_proto_goTypes = nil
	file_server_mail_proto_depIdxs = nil
}
