[hashids]
length = 12
secret = '6ab6122836cfef95f8db'

[language]
local = 'zh-cn'

[mail]
host = 'smtp.126.com'
pass = 'UFJNUIGZXYXECBJF'
port = 465
to = '188267943@qq.com'
user = 'evan_yxw@126.com'

[mysql]
[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.read]
addr = 'host.docker.internal:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[mysql.write]
addr = 'host.docker.internal:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[redis]
addr = 'host.docker.internal:6379'
db = '0'
maxretries = 3
minidleconns = 5
pass = ''
poolsize = 10
isCluster = false

[etcd]
address = ['host.docker.internal:2379']
namespace='default'
secret= ''

[server]
address = ':8023'
maxConnNum=100
buffSize=100
pprof=true
pprofAddress = ':6060'

[rpc]
address = ':8024'