autoStart=false
innerPort=10001
outPort=30000
htCheck=30
htTimeout=60
pprofPort = 6060

[server]
name = "agent"
minport=18201
maxport=18300
version = "1.0.0"

[etcd]
addr = ["127.0.0.1:2379"]
user = ""
pass = ""

[hashids]
length = 12
secret = '6ab6122836cfef95f8db'

[language]
local = 'zh-cn'

[mail]
host = 'smtp.126.com'
pass = 'UFJNUIGZXYXECBJF'
port = 465
to = '188267943@qq.com'
user = 'evan_yxw@126.com'

[mysql]
[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.read]
addr = '127.0.0.1:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[mysql.write]
addr = '127.0.0.1:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[redis]
addr = '127.0.0.1:6379'
db = '0'
maxretries = 3
minidleconns = 5
pass = ''
poolsize = 10
isCluster = false


[center]
ip = ''
port=8023
address = ':8023'
maxConnNum=10000
buffSize=100
pprof=true
pprofAddress = '127.0.0.1:6060'

[rpc]
address = ':8024'

[[ServerList]]
Name = "网关服"
EPName = "gate"
DBMongoId = 0
RedisId = 0

[[ServerList]]
Name = "管理服"
EPName = "world"
DBMongoId = 0
RedisId = 0
