[hashids]
length = 12
secret = '6ab6122836cfef95f8db'

[language]
local = 'zh-cn'

[mail]
host = 'smtp.163.com'
pass = ''
port = 465
to = ''
user = ''

[mysql]
[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.read]
addr = '127.0.0.1:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[mysql.write]
addr = '127.0.0.1:3306'
name = 'guangfu'
pass = '123456'
user = 'root'

[redis]
addr = '127.0.0.1:6379'
db = '0'
maxretries = 3
minidleconns = 5
pass = ''
poolsize = 10
isCluster = false

[etcd]
address = ['127.0.0.1:2379']
namespace='default'
secret= ''

[server]
address = ':8023'
maxConnNum=100
buffSize=100
pprof=true
pprofAddress = ':6060'